site_name: Cyferpiper's Trading Notebook
theme:
    name: material
    custom_dir: 'material'
repo_url: "https://github.com/cyferpiper/trading-notebook"
pages:
    - Home: index.md
    - General:
      - Order Types: general/order-types.md
      - Terminology: general/terminology.md
      - Market Manipulation: general/market-manipulation.md
      - Trade Strategy: general/trade-strategy.md
    - Indicators:
        - MACD: indicators/macd.md
    - Technical Analysis:
      - Patterns & Signals:
        - Double Bottoms & Tops: technical-analysis/patterns-and-signals/double-bottoms-and-tops.md
        - Head & Shoulders: technical-analysis/patterns-and-signals/head-and-shoulders.md
