site_name: Cyferpiper's Trading Notebook
theme:
    name: material
    custom_dir: 'material'
repo_url: "https://github.com/cyferpiper/trading-notebook"
pages:
    - Home: index.md
    - General:
      - Terminology: general/terminology.md
      - Order Types: general/order-types.md
      - Bankroll Management: general/bankroll-management.md
      - Trade Strategy: general/trade-strategy.md
      - Market Manipulation: general/market-manipulation.md
    - Indicators:
        - MACD: indicators/macd.md
    - Patterns & Signals:
      - Double Bottoms & Tops: patterns-and-signals/double-bottoms-and-tops.md
      - Head & Shoulders: patterns-and-signals/head-and-shoulders.md
